import { Product, AutoBuyRule, Order, UserSettings } from './types';

export const INITIAL_USER_SETTINGS: UserSettings = {
  maxSingleItemLimit: 500,
  monthlySpendLimit: 2500,
  monthlySpent: 649.99,
  requireApprovalOver: 200,
  autoBuyEnabled: true,
  smsNotifications: true,
  emailNotifications: true,
  preferredStores: ['Amazon', 'Best Buy', 'B&H Photo', 'Target'],
  shippingAddress: {
    name: 'Alex Johnson',
    street: '742 Evergreen Terrace',
    city: 'San Francisco',
    state: 'CA',
    zip: '94107',
  },
  paymentMethod: {
    type: 'Credit Card',
    last4: '4829',
    expiry: '08/28',
    brand: 'Visa Infinite',
  },
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-sony-wh1000xm5',
    name: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones',
    category: 'Audio',
    brand: 'Sony',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80',
    description: 'Industry-leading noise canceling headphones with two processors, 8 microphones, and up to 30-hour battery life.',
    rating: 4.7,
    reviewCount: 3840,
    specs: {
      'Battery Life': '30 Hours',
      'Noise Canceling': 'Industry Leading Auto NC',
      'Bluetooth': 'v5.2',
      'Weight': '250g',
      'Microphones': '8 Beamforming Mics',
    },
    retailers: [
      {
        id: 'ret-1',
        name: 'Amazon',
        logo: '📦',
        price: 328.00,
        originalPrice: 399.99,
        shipping: 'Free Prime One-Day',
        shippingCost: 0,
        deliveryEstimate: 'Tomorrow',
        inStock: true,
        sellerRating: 4.9,
        returnPolicy: '30-day Free Returns',
        url: 'https://amazon.com',
        isBestValue: true,
      },
      {
        id: 'ret-2',
        name: 'Best Buy',
        logo: '🏷️',
        price: 349.99,
        originalPrice: 399.99,
        shipping: 'Free Store Pickup / Standard',
        shippingCost: 0,
        deliveryEstimate: '2 Days',
        inStock: true,
        sellerRating: 4.8,
        returnPolicy: '15-day Returns',
        url: 'https://bestbuy.com',
      },
      {
        id: 'ret-3',
        name: 'B&H Photo',
        logo: '📷',
        price: 338.00,
        originalPrice: 399.99,
        shipping: 'Free Expedited',
        shippingCost: 0,
        deliveryEstimate: '2-3 Days',
        inStock: true,
        sellerRating: 4.9,
        returnPolicy: '30-day Returns',
        url: 'https://bhphotovideo.com',
      },
      {
        id: 'ret-4',
        name: 'eBay',
        logo: '🏷️',
        price: 299.99,
        originalPrice: 399.99,
        shipping: 'Standard Shipping',
        shippingCost: 9.99,
        deliveryEstimate: '4 Days',
        inStock: true,
        sellerRating: 4.6,
        returnPolicy: 'Seller 14-day',
        url: 'https://ebay.com',
      },
    ],
    sentiment: {
      overallScore: 92,
      trustScore: 95,
      verifiedPercentage: 88,
      pros: [
        'Unmatched Active Noise Cancellation for airplane & office noise',
        'Exceptional call quality with 8 beamforming microphones',
        'Lightweight design comfortable for 8+ hour sessions',
        'Multipoint connection switches effortlessly between phone & laptop',
      ],
      cons: [
        'Earcups no longer fold into a ultra-compact shape like XM4',
        'Slightly higher price tag than competitors',
      ],
      featureRatings: [
        { feature: 'Noise Cancellation', score: 4.9 },
        { feature: 'Sound Quality', score: 4.7 },
        { feature: 'Comfort & Fit', score: 4.6 },
        { feature: 'Battery Life', score: 4.8 },
        { feature: 'Mic Call Quality', score: 4.8 },
      ],
      summaryText: 'Analyzed 3,840 verified customer reviews across 4 major storefronts. Over 91% of buyers praise the ANC performance and call clarity. Highly recommended purchase at the current discounted price of $328.00.',
      verdict: 'Must Buy',
    },
    priceHistory: [
      { date: 'Mar 1', price: 399.99, retailer: 'Amazon' },
      { date: 'Apr 1', price: 378.00, retailer: 'Amazon' },
      { date: 'May 1', price: 399.99, retailer: 'Amazon' },
      { date: 'Jun 1', price: 348.00, retailer: 'Amazon' },
      { date: 'Jul 1', price: 358.00, retailer: 'Amazon' },
      { date: 'Aug 1', price: 328.00, retailer: 'Amazon' },
    ],
    predictedPriceDrop: {
      expectedPrice: 299.00,
      daysAway: 14,
      confidence: 84,
    },
  },
  {
    id: 'prod-keychron-q1pro',
    name: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
    category: 'Computer Peripherals',
    brand: 'Keychron',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    description: 'Full aluminum QMK/VIA wireless custom mechanical keyboard with double-gasket design and hot-swappable switches.',
    rating: 4.8,
    reviewCount: 1290,
    specs: {
      'Connectivity': 'Bluetooth 5.1 & Type-C',
      'Body Material': 'Full CNC Aluminum',
      'Switches': 'Keychron K Pro Banana / Red / Brown',
      'Battery': '4000 mAh',
      'Weight': '1.73 kg',
    },
    retailers: [
      {
        id: 'ret-k1',
        name: 'Amazon',
        logo: '📦',
        price: 189.99,
        originalPrice: 219.99,
        shipping: 'Free Prime',
        shippingCost: 0,
        deliveryEstimate: '2 Days',
        inStock: true,
        sellerRating: 4.8,
        returnPolicy: '30-day Returns',
        url: 'https://amazon.com',
      },
      {
        id: 'ret-k2',
        name: 'Keychron Direct',
        logo: '⌨️',
        price: 179.99,
        originalPrice: 219.99,
        shipping: 'Standard Express',
        shippingCost: 12.00,
        deliveryEstimate: '5-7 Days',
        inStock: true,
        sellerRating: 4.9,
        returnPolicy: '30-day Factory Return',
        url: 'https://keychron.com',
        isBestValue: true,
      },
    ],
    sentiment: {
      overallScore: 95,
      trustScore: 97,
      verifiedPercentage: 92,
      pros: [
        'Premium heavy aluminum chassis with zero flex',
        'Satisfying deep acoustic thock out of the box',
        'Flawless QMK/VIA custom key remapping',
      ],
      cons: [
        'Heavy keyboard intended for stationary desk setups',
        'Stock keycaps are solid but basic PBT',
      ],
      featureRatings: [
        { feature: 'Build Quality', score: 5.0 },
        { feature: 'Typing Acoustics', score: 4.8 },
        { feature: 'Software Customization', score: 4.9 },
        { feature: 'Battery Life', score: 4.4 },
      ],
      summaryText: 'Cross-referenced enthusiast reviews and forum sentiment. Outstanding rating for acoustics and build durability.',
      verdict: 'Must Buy',
    },
    priceHistory: [
      { date: 'Mar 1', price: 219.99, retailer: 'Keychron Direct' },
      { date: 'May 1', price: 199.99, retailer: 'Keychron Direct' },
      { date: 'Jul 1', price: 189.99, retailer: 'Amazon' },
      { date: 'Aug 1', price: 179.99, retailer: 'Keychron Direct' },
    ],
  },
  {
    id: 'prod-lg-c3-oled',
    name: 'LG C3 55-inch Class OLED evo 4K Smart TV',
    category: 'Home Theater',
    brand: 'LG',
    image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&auto=format&fit=crop&q=80',
    description: 'Self-lit OLED pixels, α9 AI Processor Gen6, 120Hz refresh rate with G-SYNC and FreeSync support for gaming.',
    rating: 4.9,
    reviewCount: 4520,
    specs: {
      'Display': '55" OLED evo 4K',
      'Refresh Rate': '120Hz Native',
      'Processor': 'α9 AI Processor Gen6',
      'HDMI Ports': '4x HDMI 2.1 (48Gbps)',
      'HDR': 'Dolby Vision, HDR10, HLG',
    },
    retailers: [
      {
        id: 'ret-tv1',
        name: 'Best Buy',
        logo: '🏷️',
        price: 1299.99,
        originalPrice: 1699.99,
        shipping: 'Free Scheduled Delivery',
        shippingCost: 0,
        deliveryEstimate: '3 Days',
        inStock: true,
        sellerRating: 4.9,
        returnPolicy: '15-day Returns / TV haul-away option',
        url: 'https://bestbuy.com',
        isBestValue: true,
      },
      {
        id: 'ret-tv2',
        name: 'Amazon',
        logo: '📦',
        price: 1346.99,
        originalPrice: 1699.99,
        shipping: 'Free White Glove Delivery',
        shippingCost: 0,
        deliveryEstimate: '4 Days',
        inStock: true,
        sellerRating: 4.8,
        returnPolicy: '30-day Returns',
        url: 'https://amazon.com',
      },
    ],
    sentiment: {
      overallScore: 96,
      trustScore: 94,
      verifiedPercentage: 91,
      pros: [
        'Infinite contrast ratio with perfect deep blacks',
        'Flawless 120Hz gaming with 4 full HDMI 2.1 ports',
        'Bright OLED panel enhanced by α9 AI processor',
      ],
      cons: [
        'Built-in speakers are average; external soundbar recommended',
      ],
      featureRatings: [
        { feature: 'Picture Quality', score: 5.0 },
        { feature: 'Gaming Features', score: 5.0 },
        { feature: 'Brightness', score: 4.6 },
        { feature: 'Smart Interface', score: 4.5 },
      ],
      summaryText: 'Aggregated reviews from tech critics and RTINGS calibration scores. Best-in-class TV for movie lovers and next-gen console gamers.',
      verdict: 'Must Buy',
    },
    priceHistory: [
      { date: 'Mar 1', price: 1699.99, retailer: 'Best Buy' },
      { date: 'May 1', price: 1499.99, retailer: 'Best Buy' },
      { date: 'Jul 1', price: 1399.99, retailer: 'Best Buy' },
      { date: 'Aug 1', price: 1299.99, retailer: 'Best Buy' },
    ],
  },
  {
    id: 'prod-anker-prime-20k',
    name: 'Anker Prime 20,000mAh Power Bank (200W Output)',
    category: 'Electronics',
    brand: 'Anker',
    image: 'https://images.unsplash.com/photo-1609592424074-b52b2f6b43d3?w=600&auto=format&fit=crop&q=80',
    description: 'Multi-device ultra-fast charging battery bank with smart digital display and 100W dual USB-C charging.',
    rating: 4.6,
    reviewCount: 940,
    specs: {
      'Capacity': '20,000 mAh',
      'Max Output': '200W Total',
      'Ports': '2x USB-C, 1x USB-A',
      'Display': 'Smart Color OLED Screen',
      'Recharge Speed': '100W Quick Recharge',
    },
    retailers: [
      {
        id: 'ret-a1',
        name: 'Amazon',
        logo: '📦',
        price: 89.99,
        originalPrice: 129.99,
        shipping: 'Free Same-Day Prime',
        shippingCost: 0,
        deliveryEstimate: 'Today by 9PM',
        inStock: true,
        sellerRating: 4.9,
        returnPolicy: '30-day Free Returns',
        url: 'https://amazon.com',
        isBestValue: true,
      },
      {
        id: 'ret-a2',
        name: 'Target',
        logo: '🎯',
        price: 109.99,
        originalPrice: 129.99,
        shipping: 'Free 2-Day',
        shippingCost: 0,
        deliveryEstimate: '2 Days',
        inStock: true,
        sellerRating: 4.7,
        returnPolicy: '90-day Returns',
        url: 'https://target.com',
      },
    ],
    sentiment: {
      overallScore: 89,
      trustScore: 98,
      verifiedPercentage: 94,
      pros: [
        'Charges MacBook Pro and iPhone simultaneously at top speed',
        'Real-time OLED display shows exact wattages and battery temp',
        'TSA approved for airplane carry-on luggage',
      ],
      cons: [
        'Includes high speed cable but charging base sold separately',
      ],
      featureRatings: [
        { feature: 'Charging Speed', score: 5.0 },
        { feature: 'Portability', score: 4.5 },
        { feature: 'Display Utility', score: 4.9 },
      ],
      summaryText: 'Verified power users rank this as the top travel power bank for laptops and phones.',
      verdict: 'Good Value',
    },
    priceHistory: [
      { date: 'May 1', price: 129.99, retailer: 'Amazon' },
      { date: 'Jun 1', price: 109.99, retailer: 'Amazon' },
      { date: 'Aug 1', price: 89.99, retailer: 'Amazon' },
    ],
  },
];

export const INITIAL_RULES: AutoBuyRule[] = [
  {
    id: 'rule-1',
    productName: 'Sony WH-1000XM5 Noise Canceling Headphones',
    category: 'Audio',
    targetPrice: 300.00,
    currentLowestPrice: 328.00,
    maxBudget: 350.00,
    requireApproval: false,
    minRating: 4.5,
    status: 'active',
    createdAt: '2026-08-10',
    lastChecked: '5 mins ago',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'rule-2',
    productName: 'Keychron Q1 Pro Mechanical Keyboard',
    category: 'Peripherals',
    targetPrice: 175.00,
    currentLowestPrice: 179.99,
    maxBudget: 200.00,
    requireApproval: true,
    minRating: 4.6,
    status: 'active',
    createdAt: '2026-08-15',
    lastChecked: '12 mins ago',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-10492',
    orderNumber: 'ABA-89302-US',
    productId: 'prod-anker-prime-20k',
    productName: 'Anker Prime 20,000mAh Power Bank (200W Output)',
    productImage: 'https://images.unsplash.com/photo-1609592424074-b52b2f6b43d3?w=300&auto=format&fit=crop&q=80',
    retailer: 'Amazon',
    pricePaid: 89.99,
    shippingCost: 0,
    tax: 7.20,
    total: 97.19,
    purchasedAt: '2026-08-18 14:32',
    status: 'delivered',
    trackingNumber: 'TBA309182390192',
    estimatedDelivery: '2026-08-19',
    agentReasoning: 'Trigger condition met: Price dropped to $89.99 (below $95 limit). Amazon Prime same-day selected for best speed and lowest price.',
    autoPurchased: true,
  },
  {
    id: 'ord-10441',
    orderNumber: 'ABA-77104-US',
    productId: 'prod-logitech-mx3a',
    productName: 'Logitech MX Master 3S Wireless Performance Mouse',
    productImage: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=300&auto=format&fit=crop&q=80',
    retailer: 'Best Buy',
    pricePaid: 99.99,
    shippingCost: 0,
    tax: 8.00,
    total: 107.99,
    purchasedAt: '2026-08-05 10:15',
    status: 'delivered',
    trackingNumber: '1Z9999999999999999',
    estimatedDelivery: '2026-08-07',
    agentReasoning: 'Manual approval confirmed by user Alex Johnson. Best Buy offered immediate local pickup option.',
    autoPurchased: false,
  },
];
