import { Product, AutoBuyRule, Order, UserSettings } from './types';

export const INITIAL_USER_SETTINGS: UserSettings = {
  maxSingleItemLimit: 50000,
  monthlySpendLimit: 250000,
  monthlySpent: 64990,
  requireApprovalOver: 15000,
  autoBuyEnabled: true,
  smsNotifications: true,
  emailNotifications: true,
  preferredStores: ['Amazon India', 'Flipkart', 'Croma', 'Reliance Digital'],
  shippingAddress: {
    name: 'Alex Johnson',
    street: '742 Evergreen Terrace',
    city: 'San Francisco',
    state: 'CA',
    zip: '94107',
  },
  paymentMethod: {
    type: 'Credit Card',
    last4: '4829',
    expiry: '08/28',
    brand: 'Visa Infinite',
  },
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-sony-wh1000xm5',
    name: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones',
    category: 'Audio',
    brand: 'Sony',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80',
    description: 'Industry-leading noise canceling headphones with two processors, 8 microphones, and up to 30-hour battery life.',
    rating: 4.7,
    reviewCount: 3840,
    specs: {
      'Battery Life': '30 Hours',
      'Noise Canceling': 'Industry Leading Auto NC',
      'GST Invoice': 'Available (Tax Credit)',
      'India Warranty': '1-Year Official Sony India Warranty',
    },
    retailers: [
      {
        id: 'ret-1',
        name: 'Amazon India',
        logo: '📦',
        price: 26990,
        originalPrice: 34990,
        shipping: 'Free Prime 1-Day Delivery',
        shippingCost: 0,
        deliveryEstimate: 'Tomorrow',
        inStock: true,
        sellerRating: 4.9,
        returnPolicy: '7-day Replacement Guarantee',
        url: 'https://amazon.in',
        isBestValue: true,
      },
      {
        id: 'ret-2',
        name: 'Flipkart',
        logo: '🛍️',
        price: 27490,
        originalPrice: 34990,
        shipping: 'Free Plus Express Delivery',
        shippingCost: 0,
        deliveryEstimate: '2 Days',
        inStock: true,
        sellerRating: 4.8,
        returnPolicy: '7-day Replacement Guarantee',
        url: 'https://flipkart.com',
      },
      {
        id: 'ret-3',
        name: 'Croma',
        logo: '🏪',
        price: 27990,
        originalPrice: 34990,
        shipping: 'Free Store Pickup / Same Day',
        shippingCost: 0,
        deliveryEstimate: 'Same Day',
        inStock: true,
        sellerRating: 4.9,
        returnPolicy: '7-day Replacement Guarantee',
        url: 'https://croma.com',
      },
    ],
    sentiment: {
      overallScore: 92,
      trustScore: 95,
      verifiedPercentage: 88,
      pros: [
        'Unmatched Active Noise Cancellation for flights & busy office',
        'Exceptional call quality with 8 beamforming microphones',
        'Lightweight design comfortable for 8+ hour work sessions',
      ],
      cons: [
        'Earcups fold flat but do not collapse into ultra-small case',
      ],
      featureRatings: [
        { feature: 'Noise Cancellation', score: 4.9 },
        { feature: 'Sound Quality', score: 4.7 },
        { feature: 'Comfort & Fit', score: 4.6 },
        { feature: 'Battery Life', score: 4.8 },
      ],
      summaryText: 'Analyzed 3,840 verified customer reviews across Amazon India & Flipkart. Over 91% of buyers praise the ANC performance and call clarity.',
      verdict: 'Must Buy',
    },
    priceHistory: [
      { date: '3 Months Ago', price: 34990, retailer: 'Amazon India' },
      { date: '2 Months Ago', price: 29990, retailer: 'Amazon India' },
      { date: 'Last Month', price: 28490, retailer: 'Amazon India' },
      { date: 'Current Best', price: 26990, retailer: 'Amazon India' },
    ],
    predictedPriceDrop: {
      expectedPrice: 24990,
      daysAway: 12,
      confidence: 86,
    },
  },
  {
    id: 'prod-keychron-q1pro',
    name: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
    category: 'Computer Peripherals',
    brand: 'Keychron',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    description: 'Full aluminum QMK/VIA wireless custom mechanical keyboard with double-gasket design and hot-swappable switches.',
    rating: 4.8,
    reviewCount: 1290,
    specs: {
      'Connectivity': 'Bluetooth 5.1 & Type-C',
      'Body Material': 'Full CNC Aluminum',
      'Switches': 'Keychron K Pro Mechanical',
      'Warranty': '1-Year Keychron India Warranty',
    },
    retailers: [
      {
        id: 'ret-k1',
        name: 'Amazon India',
        logo: '📦',
        price: 15999,
        originalPrice: 18999,
        shipping: 'Free Prime Express',
        shippingCost: 0,
        deliveryEstimate: '2 Days',
        inStock: true,
        sellerRating: 4.8,
        returnPolicy: '7-day Replacement',
        url: 'https://amazon.in',
      },
      {
        id: 'ret-k2',
        name: 'Keychron Direct',
        logo: '⌨️',
        price: 14999,
        originalPrice: 18999,
        shipping: 'Free Standard Express',
        shippingCost: 0,
        deliveryEstimate: '4 Days',
        inStock: true,
        sellerRating: 4.9,
        returnPolicy: '14-day Factory Guarantee',
        url: 'https://keychron.in',
        isBestValue: true,
      },
    ],
    sentiment: {
      overallScore: 95,
      trustScore: 97,
      verifiedPercentage: 92,
      pros: [
        'Premium heavy aluminum chassis with zero flex',
        'Satisfying deep acoustic thock out of the box',
        'Flawless QMK/VIA custom key remapping',
      ],
      cons: [
        'Heavy keyboard intended for stationary desk setups',
      ],
      featureRatings: [
        { feature: 'Build Quality', score: 5.0 },
        { feature: 'Typing Acoustics', score: 4.8 },
        { feature: 'Software Customization', score: 4.9 },
      ],
      summaryText: 'Outstanding rating for acoustics and build durability.',
      verdict: 'Must Buy',
    },
    priceHistory: [
      { date: '3 Months Ago', price: 18999, retailer: 'Keychron Direct' },
      { date: 'Current Best', price: 14999, retailer: 'Keychron Direct' },
    ],
  },
];

export const INITIAL_RULES: AutoBuyRule[] = [
  {
    id: 'rule-1',
    productName: 'Sony WH-1000XM5 Noise Canceling Headphones',
    category: 'Audio',
    targetPrice: 24990,
    currentLowestPrice: 26990,
    maxBudget: 30000,
    requireApproval: false,
    minRating: 4.5,
    status: 'active',
    createdAt: '2026-08-10',
    lastChecked: '5 mins ago',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'rule-2',
    productName: 'Keychron Q1 Pro Mechanical Keyboard',
    category: 'Peripherals',
    targetPrice: 14500,
    currentLowestPrice: 15999,
    maxBudget: 18000,
    requireApproval: true,
    minRating: 4.6,
    status: 'active',
    createdAt: '2026-08-15',
    lastChecked: '12 mins ago',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-10492',
    orderNumber: 'ABA-89302-IN',
    productId: 'prod-anker-prime-20k',
    productName: 'Anker Prime 20,000mAh Power Bank (200W Output)',
    productImage: 'https://images.unsplash.com/photo-1609592424074-b52b2f6b43d3?w=300&auto=format&fit=crop&q=80',
    retailer: 'Amazon India',
    pricePaid: 7649,
    shippingCost: 0,
    tax: 612,
    total: 8261,
    purchasedAt: '2026-08-18 14:32',
    status: 'delivered',
    trackingNumber: 'TBA309182390192',
    estimatedDelivery: '2026-08-19',
    agentReasoning: 'Trigger condition met: Price dropped to ₹7,649 (below ₹8,000 limit). Amazon India Prime same-day selected.',
    autoPurchased: true,
  },
  {
    id: 'ord-10441',
    orderNumber: 'ABA-77104-IN',
    productId: 'prod-logitech-mx3a',
    productName: 'Logitech MX Master 3S Wireless Mouse',
    productImage: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=300&auto=format&fit=crop&q=80',
    retailer: 'Flipkart',
    pricePaid: 8499,
    shippingCost: 0,
    tax: 680,
    total: 9179,
    purchasedAt: '2026-08-05 10:15',
    status: 'delivered',
    trackingNumber: 'FKB999999999999',
    estimatedDelivery: '2026-08-07',
    agentReasoning: 'Manual approval confirmed by user Alex Johnson. Flipkart offered immediate delivery.',
    autoPurchased: false,
  },
];
